### ISSUE TITLE
Please support default values in _config.yml

### ISSUE THREAD

**Issue by mariusa** [cyjake/darko#19]
_config.yml can have
```
defaults:
  -
    values:
      layout: "default"


```

This way, there's no need to specify in every html
```
---
layout: default
---

```

This works in jekyll, but not darko.
